"""crear tablas vehicles y drivers

Revision ID: a7b69aeffaea
Revises: 
Create Date: 2026-09-17 23:13:28.925799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7b69aeffaea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehiculos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('placa', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('capacidad_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacidad_m3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('vencimiento_seguro', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('capacidad_refrigeracion', sa.Boolean(), nullable=False),
    sa.Column('certificado_hazmat', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    op.create_table('conductores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('licencia_numero', sa.String(length=50), nullable=False),
    sa.Column('categorias_licencia', sa.String(length=100), nullable=True),
    sa.Column('certificacion_hazmat', sa.Boolean(), nullable=False),
    sa.Column('vehiculo_id', sa.UUID(), nullable=True),
    sa.Column('horas_semanales', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('licencia_numero')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conductores')
    op.drop_table('vehiculos')
    # ### end Alembic commands ###
